KafkaServer {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="admin-secret"
   user_admin="admin-secret";
   user_kafka_broker="kafka-broker-secret"
   user_monitoring="monitoring-secret"
};
KafkaClient {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="client"
   password="client-secret";
};
Client {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="client"
   password="client-secret";
};
